### ISSUE TITLE
unable to view twitch streams

### ISSUE THREAD

**Issue by kevbob1** [chatrealm/DctvAndroid#14]
make viewing twitch streams more reliable.  often it fails when trying to load hls4 stream.

**Comment by RenAigu** [comment]
This is an API problem, the DC API and Twitch API are not on speaking terms. Had a chat with the Sgt about it. The redirect from Twitch broke, in his IOS app he said he just put in a webview as he didn't feel like fixing the api at that time. Don't know if a webview will work elegantly on here though.

**Comment by kevbob1** [comment]
my plan is to implement what DC API redirect does inside the Android app.  The benefit is we can allow the user to switch stream qualities.  I already have a twitch app key to use.  Just need to code it up.

**Comment by Excape** [comment]
Don't know if an implementation through HLS will be robust enough. Twitch is probably not the biggest fan, they can't show any ads..

And it's against [Twitch's API TOS](https://www.twitch.tv/p/api_terms_of_service):

```
13 Prohibitions 
f.
 access any portion of any Twitch audiovisual content by any means other than use of the Twitch Player;
```

**Comment by kevbob1** [comment]
welp,  webview it is.

https://player.twitch.tv/?channel=%s

**Comment by Excape** [comment]
Maybe a starting point:
http://stackoverflow.com/questions/30313933/playing-twitch-tv-video-within-android-app-android-studio-development

**Comment by kevbob1** [comment]
I have assurances for Sgtmuffin (Dan) that twitch redirect will be fixed real soon now.  will close this once it is verified.

**Comment by kevbob1** [comment]
fixed and supports quality switching also.
